// Flora plant-food catalog: canonical ids, display names, and search aliases.
import type { Category } from "../domain/category";

export interface CatalogFood {
  id: string;
  name: string;
  category: Category;
  aliases: readonly string[];
}

function food(
  id: string,
  name: string,
  category: Category,
  aliases: readonly string[] = [],
): CatalogFood {
  return { id, name, category, aliases };
}

export const catalog: readonly CatalogFood[] = [
  food("acai", "Açaí", "berry", ["acai berry"]),
  food("adzuki", "Adzuki", "legume", ["adzuki bean", "red bean adzuki"]),
  food("allspice", "Allspice", "spice", ["pimento berry"]),
  food("almond", "Almond", "nut", ["almond butter", "almond milk"]),
  food("amaranth", "Amaranth", "grain", []),
  food("apple", "Apple", "fruit", ["granny smith", "gala", "fuji"]),
  food("apricot", "Apricot", "fruit", []),
  food("artichoke", "Artichoke", "vegetable", []),
  food("arugula", "Arugula", "vegetable", ["rocket"]),
  food("asparagus", "Asparagus", "vegetable", []),
  food("avocado", "Avocado", "fruit", []),
  food("banana", "Banana", "fruit", ["plantain"]),
  food("barley", "Barley", "grain", ["pearl barley"]),
  food("basil", "Basil", "herb", ["sweet basil"]),
  food("bay-leaf", "Bay leaf", "herb", ["bay leaves"]),
  food("beet", "Beet", "vegetable", ["beetroot"]),
  food("bell-pepper", "Bell pepper", "vegetable", [
    "red bell pepper",
    "yellow bell pepper",
    "green bell pepper",
    "sweet pepper",
  ]),
  food("bilberry", "Bilberry", "berry", ["blåbær", "blaabaer", "whortleberry"]),
  food("black-eyed-pea", "Black-eyed pea", "legume", ["cowpea"]),
  food("black-pepper", "Black pepper", "spice", ["white pepper", "peppercorn"]),
  food("blackberry", "Blackberry", "berry", []),
  food("blueberry", "Blueberry", "berry", ["highbush blueberry"]),
  food("bok-choy", "Bok choy", "vegetable", ["pak choi", "pak choy"]),
  food("boysenberry", "Boysenberry", "berry", []),
  food("broccoli", "Broccoli", "vegetable", ["broccolini", "tenderstem"]),
  food("brussels-sprout", "Brussels sprout", "vegetable", ["brussels sprouts"]),
  food("buckwheat", "Buckwheat", "grain", ["kasha"]),
  food("butternut-squash", "Butternut squash", "vegetable", []),
  food("button-mushroom", "Button mushroom", "other", ["cremini", "portobello", "champignon"]),
  food("cabbage", "Cabbage", "vegetable", ["green cabbage", "red cabbage"]),
  food("cardamom", "Cardamom", "spice", ["green cardamom"]),
  food("carrot", "Carrot", "vegetable", []),
  food("cassava", "Cassava", "vegetable", ["yuca", "manioc"]),
  food("cauliflower", "Cauliflower", "vegetable", ["romanesco"]),
  food("celeriac", "Celeriac", "vegetable", ["celery root"]),
  food("celery", "Celery", "vegetable", ["celery seed"]),
  food("chard", "Chard", "vegetable", ["swiss chard", "silverbeet"]),
  food("chia", "Chia", "seed", ["chia seeds", "chia seed"]),
  food("chickpea", "Chickpea", "legume", ["hummus", "garbanzo", "garbanzo bean"]),
  food("chicory", "Chicory", "vegetable", ["endive chicory"]),
  food("chili", "Chili", "vegetable", [
    "chilli",
    "chile",
    "jalapeño",
    "jalapeno",
    "cayenne",
    "paprika",
    "chili flakes",
    "chilli flakes",
  ]),
  food("chives", "Chives", "herb", ["chive"]),
  food("cinnamon", "Cinnamon", "spice", ["cinnamon stick", "ground cinnamon"]),
  food("cloudberry", "Cloudberry", "berry", ["multe", "bakeapple"]),
  food("clove", "Clove", "spice", ["cloves"]),
  food("cocoa", "Cocoa", "other", ["cacao", "dark chocolate", "cocoa powder"]),
  food("coconut", "Coconut", "fruit", ["coconut meat"]),
  food("coffee", "Coffee", "other", ["espresso", "decaf", "decaffeinated coffee"]),
  food("common-bean", "Common bean", "legume", [
    "black bean",
    "kidney bean",
    "pinto bean",
    "green bean",
    "french bean",
    "navy bean",
    "cannellini bean",
    "great northern bean",
  ]),
  food("coriander", "Coriander", "herb", ["cilantro", "coriander seed", "coriander leaves"]),
  food("corn", "Corn", "grain", ["sweetcorn", "polenta", "popcorn", "maize"]),
  food("cranberry", "Cranberry", "berry", []),
  food("cucumber", "Cucumber", "vegetable", []),
  food("cumin", "Cumin", "spice", ["cumin seed"]),
  food("currant", "Currant", "berry", ["black currant", "red currant"]),
  food("date", "Date", "fruit", []),
  food("dill", "Dill", "herb", ["dill weed"]),
  food("dragon-fruit", "Dragon fruit", "fruit", ["pitaya", "pitahaya"]),
  food("eggplant", "Eggplant", "vegetable", ["aubergine"]),
  food("elderberry", "Elderberry", "berry", []),
  food("endive", "Endive", "vegetable", ["belgian endive"]),
  food("fava", "Fava", "legume", ["fava bean", "broad bean"]),
  food("fennel", "Fennel", "vegetable", ["fennel seed", "fennel bulb"]),
  food("fenugreek", "Fenugreek", "spice", ["fenugreek seed"]),
  food("fig", "Fig", "fruit", []),
  food("flax", "Flax", "seed", ["flaxseed", "linseed", "flax seed"]),
  food("garlic", "Garlic", "vegetable", ["garlic powder"]),
  food("ginger", "Ginger", "spice", ["ginger root", "fresh ginger"]),
  food("gooseberry", "Gooseberry", "berry", []),
  food("grape", "Grape", "fruit", ["raisin", "sultana"]),
  food("grapefruit", "Grapefruit", "fruit", []),
  food("guava", "Guava", "fruit", []),
  food("hazelnut", "Hazelnut", "nut", ["filbert"]),
  food("heart-of-palm", "Heart of palm", "vegetable", ["palm heart"]),
  food("horseradish", "Horseradish", "vegetable", []),
  food("hubbard-squash", "Hubbard squash", "vegetable", []),
  food("jicama", "Jicama", "vegetable", ["yam bean"]),
  food("kale", "Kale", "vegetable", ["collard greens", "collards", "collard"]),
  food("kiwi", "Kiwi", "fruit", ["kiwifruit", "kiwi fruit"]),
  food("kohlrabi", "Kohlrabi", "vegetable", []),
  food("leek", "Leek", "vegetable", []),
  food("lemon", "Lemon", "fruit", []),
  food("lemongrass", "Lemongrass", "herb", ["lemon grass"]),
  food("lentil", "Lentil", "legume", ["red lentil", "green lentil"]),
  food("lettuce", "Lettuce", "vegetable", ["romaine", "iceberg lettuce"]),
  food("lime", "Lime", "fruit", ["key lime"]),
  food("lima", "Lima", "legume", ["lima bean", "butter bean"]),
  food("lingonberry", "Lingonberry", "berry", ["cowberry"]),
  food("lychee", "Lychee", "fruit", ["litchi"]),
  food("macadamia", "Macadamia", "nut", ["macadamia nut"]),
  food("mandarin", "Mandarin", "fruit", ["clementine", "tangerine", "mandarin orange"]),
  food("mango", "Mango", "fruit", []),
  food("marjoram", "Marjoram", "herb", ["sweet marjoram"]),
  food("melon", "Melon", "fruit", ["cantaloupe", "honeydew", "rockmelon"]),
  food("millet", "Millet", "grain", ["proso millet"]),
  food("mint", "Mint", "herb", ["spearmint"]),
  food("mung", "Mung", "legume", ["mung bean", "moong bean"]),
  food("mulberry", "Mulberry", "berry", []),
  food("mustard", "Mustard", "vegetable", ["mustard seed", "mustard greens"]),
  food("nutmeg", "Nutmeg", "spice", ["mace"]),
  food("oat", "Oat", "grain", ["rolled oats", "oatmeal", "oat milk", "steel cut oats"]),
  food("okra", "Okra", "vegetable", ["lady finger"]),
  food("olive", "Olive", "fruit", []),
  food("onion", "Onion", "vegetable", [
    "shallot",
    "red onion",
    "spring onion",
    "scallion",
    "green onion",
  ]),
  food("orange", "Orange", "fruit", ["navel orange"]),
  food("oregano", "Oregano", "herb", ["wild oregano"]),
  food("oyster-mushroom", "Oyster mushroom", "other", []),
  food("papaya", "Papaya", "fruit", ["pawpaw"]),
  food("parsley", "Parsley", "herb", ["flat leaf parsley", "curly parsley"]),
  food("parsnip", "Parsnip", "vegetable", []),
  food("passion-fruit", "Passion fruit", "fruit", ["passionfruit", "maracuja"]),
  food("pattypan-squash", "Pattypan squash", "vegetable", ["scallop squash"]),
  food("pea", "Pea", "legume", ["green pea", "garden pea", "snow pea", "sugar snap pea"]),
  food("peach", "Peach", "fruit", ["nectarine"]),
  food("peanut", "Peanut", "legume", ["peanut butter", "groundnut"]),
  food("pear", "Pear", "fruit", []),
  food("pecan", "Pecan", "nut", []),
  food("persimmon", "Persimmon", "fruit", []),
  food("pine-nut", "Pine nut", "seed", ["pine nuts", "pignoli"]),
  food("pineapple", "Pineapple", "fruit", []),
  food("pistachio", "Pistachio", "nut", []),
  food("plum", "Plum", "fruit", ["prune"]),
  food("pomegranate", "Pomegranate", "fruit", []),
  food("potato", "Potato", "vegetable", ["white potato", "russet potato"]),
  food("pumpkin", "Pumpkin", "vegetable", ["pumpkin seed", "pepita"]),
  food("quinoa", "Quinoa", "grain", []),
  food("radish", "Radish", "vegetable", ["daikon", "white radish"]),
  food("rhubarb", "Rhubarb", "vegetable", []),
  food("rice", "Rice", "grain", ["white rice", "brown rice", "jasmine rice", "basmati rice"]),
  food("rosemary", "Rosemary", "herb", []),
  food("rutabaga", "Rutabaga", "vegetable", ["swede"]),
  food("rye", "Rye", "grain", ["rye berry"]),
  food("saffron", "Saffron", "spice", []),
  food("sage", "Sage", "herb", []),
  food("seaweed", "Seaweed", "other", ["nori", "wakame", "kombu", "kelp"]),
  food("sesame", "Sesame", "seed", ["tahini", "sesame seed"]),
  food("shiitake", "Shiitake", "other", ["shiitake mushroom"]),
  food("sorghum", "Sorghum", "grain", []),
  food("soy", "Soy", "legume", ["tofu", "tempeh", "edamame", "miso", "soybean"]),
  food("spinach", "Spinach", "vegetable", []),
  food("spelt", "Spelt", "grain", ["farro"]),
  food("star-anise", "Star anise", "spice", []),
  food("star-fruit", "Star fruit", "fruit", ["carambola"]),
  food("strawberry", "Strawberry", "berry", []),
  food("sweet-potato", "Sweet potato", "vegetable", ["yam"]),
  food("taro", "Taro", "vegetable", ["dasheen"]),
  food("tarragon", "Tarragon", "herb", []),
  food("tea", "Tea", "other", ["black tea", "green tea", "matcha"]),
  food("teff", "Teff", "grain", []),
  food("thyme", "Thyme", "herb", []),
  food("tomato", "Tomato", "vegetable", ["sun-dried tomato", "cherry tomato", "tomato paste"]),
  food("truffle", "Truffle", "other", ["black truffle", "white truffle"]),
  food("turmeric", "Turmeric", "spice", ["turmeric root"]),
  food("turnip", "Turnip", "vegetable", []),
  food("vanilla", "Vanilla", "spice", ["vanilla bean"]),
  food("walnut", "Walnut", "nut", ["english walnut"]),
  food("watercress", "Watercress", "vegetable", []),
  food("watermelon", "Watermelon", "fruit", []),
  food("wheat", "Wheat", "grain", ["bread", "pasta", "bulgur", "couscous", "flour", "semolina"]),
  food("wild-rice", "Wild rice", "grain", []),
  food("zucchini", "Zucchini", "vegetable", ["courgette"]),
  food("cashew", "Cashew", "nut", []),
  food("cherry", "Cherry", "fruit", ["sweet cherry", "sour cherry"]),
  food("brazil-nut", "Brazil nut", "nut", []),
  food("raspberry", "Raspberry", "berry", []),
];
