// Norwegian Bokmål display names and extra search terms for the Flora catalog.
export const NB_NAMES: Record<string, string> = {
  acai: "Açaí",
  adzuki: "Adzukibønne",
  allspice: "Allehånde",
  almond: "Mandel",
  amaranth: "Amarant",
  apple: "Eple",
  apricot: "Aprikos",
  artichoke: "Artiskokk",
  arugula: "Ruccola",
  asparagus: "Asparges",
  avocado: "Avokado",
  banana: "Banan",
  barley: "Bygg",
  basil: "Basilikum",
  "bay-leaf": "Laurbærblad",
  beet: "Rødbete",
  "bell-pepper": "Paprika",
  bilberry: "Blåbær",
  "black-eyed-pea": "Øyetbønne",
  "black-pepper": "Svart pepper",
  blackberry: "Bjørnebær",
  blueberry: "Hageblåbær",
  "bok-choy": "Pak choy",
  boysenberry: "Boysenbær",
  broccoli: "Brokkoli",
  "brussels-sprout": "Rosenkål",
  buckwheat: "Bokhvete",
  "butternut-squash": "Butternutgresskar",
  "button-mushroom": "Sjampinjong",
  cabbage: "Hodekål",
  cardamom: "Kardemomme",
  carrot: "Gulrot",
  cassava: "Kassava",
  cauliflower: "Blomkål",
  celeriac: "Sellerirot",
  celery: "Selleri",
  chard: "Mangold",
  chia: "Chia",
  chickpea: "Kikert",
  chicory: "Sikori",
  chili: "Chili",
  chives: "Gressløk",
  cinnamon: "Kanel",
  cloudberry: "Multe",
  clove: "Nellik",
  cocoa: "Kakao",
  coconut: "Kokosnøtt",
  coffee: "Kaffe",
  "common-bean": "Hagebønne",
  coriander: "Koriander",
  corn: "Mais",
  cranberry: "Tranebær",
  cucumber: "Agurk",
  cumin: "Spisskummen",
  currant: "Rips",
  date: "Daddel",
  dill: "Dill",
  "dragon-fruit": "Dragefrukt",
  eggplant: "Aubergine",
  elderberry: "Hyllebær",
  endive: "Endivie",
  fava: "Bondebønne",
  fennel: "Fennikel",
  fenugreek: "Bukkehornkløver",
  fig: "Fiken",
  flax: "Lin",
  garlic: "Hvitløk",
  ginger: "Ingefær",
  gooseberry: "Stikkelsbær",
  grape: "Drue",
  grapefruit: "Grapefrukt",
  guava: "Guava",
  hazelnut: "Hasselnøtt",
  "heart-of-palm": "Palmehjerte",
  horseradish: "Pepperrot",
  "hubbard-squash": "Hubbardgresskar",
  jicama: "Jicama",
  kale: "Grønnkål",
  kiwi: "Kiwi",
  kohlrabi: "Kålrabi",
  leek: "Purre",
  lemon: "Sitron",
  lemongrass: "Sitrongress",
  lentil: "Linse",
  lettuce: "Salat",
  lime: "Lime",
  lima: "Limabønne",
  lingonberry: "Tyttebær",
  lychee: "Litchi",
  macadamia: "Macadamianøtt",
  mandarin: "Mandarin",
  mango: "Mango",
  marjoram: "Merian",
  melon: "Melon",
  millet: "Hirse",
  mint: "Mynte",
  mung: "Mungbønne",
  mulberry: "Morbær",
  mustard: "Sennep",
  nutmeg: "Muskat",
  oat: "Havre",
  okra: "Okra",
  olive: "Oliven",
  onion: "Løk",
  orange: "Appelsin",
  oregano: "Oregano",
  "oyster-mushroom": "Østerssopp",
  papaya: "Papaya",
  parsley: "Persille",
  parsnip: "Pastinakk",
  "passion-fruit": "Pasjonsfrukt",
  "pattypan-squash": "Patisson",
  pea: "Ert",
  peach: "Fersken",
  peanut: "Peanøtt",
  pear: "Pære",
  pecan: "Pekannøtt",
  persimmon: "Kaki",
  "pine-nut": "Pinjekjerne",
  pineapple: "Ananas",
  pistachio: "Pistasjnøtt",
  plum: "Plomme",
  pomegranate: "Granateple",
  potato: "Potet",
  pumpkin: "Gresskar",
  quinoa: "Quinoa",
  radish: "Reddik",
  rhubarb: "Rabarbra",
  rice: "Ris",
  rosemary: "Rosmarin",
  rutabaga: "Kålrot",
  rye: "Rug",
  saffron: "Safran",
  sage: "Salvie",
  seaweed: "Tang",
  sesame: "Sesam",
  shiitake: "Shiitake",
  sorghum: "Sorghum",
  soy: "Soya",
  spinach: "Spinat",
  spelt: "Spelt",
  "star-anise": "Stjerneanis",
  "star-fruit": "Stjernefrukt",
  strawberry: "Jordbær",
  "sweet-potato": "Søtpotet",
  taro: "Taro",
  tarragon: "Estragon",
  tea: "Te",
  teff: "Teff",
  thyme: "Timian",
  tomato: "Tomat",
  truffle: "Trøffel",
  turmeric: "Gurkemeie",
  turnip: "Nepe",
  vanilla: "Vanilje",
  walnut: "Valnøtt",
  watercress: "Brønnkarse",
  watermelon: "Vannmelon",
  wheat: "Hvete",
  "wild-rice": "Villris",
  zucchini: "Squash",
  cashew: "Cashewnøtt",
  cherry: "Kirsebær",
  "brazil-nut": "Paranøtt",
  raspberry: "Bringebær",
};

export const NB_SEARCH: Record<string, readonly string[]> = {
  allspice: ["jamaicapepper"],
  almond: ["mandelsmør", "mandelmelk", "mandelflak", "mandelmel"],
  apple: ["eplemos"],
  arugula: ["rucola"],
  banana: ["kokebanan", "melbanan"],
  barley: ["perlebygg", "byggmel"],
  "bay-leaf": ["laurbær"],
  beet: ["gulbete"],
  "bell-pepper": ["rød paprika", "gul paprika", "grønn paprika", "oransje paprika", "spisspaprika"],
  bilberry: ["skogblåbær"],
  "black-eyed-pea": ["øyebønne", "svarteøyebønne"],
  "black-pepper": ["sort pepper", "hvit pepper", "pepperkorn"],
  blueberry: ["amerikansk blåbær"],
  "bok-choy": ["bok choy", "pak choi"],
  broccoli: ["brokkolini", "tenderstem"],
  buckwheat: ["bokhvetemel"],
  "butternut-squash": ["butternut"],
  "button-mushroom": ["kastanjesjampinjong", "portobello", "portobellosopp", "champignon"],
  cabbage: ["hvitkål", "rødkål", "spisskål", "savoykål"],
  cassava: ["maniok"],
  cauliflower: ["romanesco"],
  celeriac: ["knollselleri"],
  celery: ["sellerifrø"],
  chard: ["bladbete"],
  chia: ["chiafrø"],
  chickpea: ["kikerter", "hummus", "kikertmel"],
  chili: ["chiliflak", "chilipulver", "cayennepepper", "jalapeño"],
  cinnamon: ["kanelstang"],
  cloudberry: ["multebær", "molte"],
  clove: ["kryddernellik"],
  cocoa: ["kakaopulver", "mørk sjokolade", "kakaobønne"],
  coconut: ["kokos", "kokosmelk", "kokosflak", "kokosmel"],
  coffee: ["espresso", "koffeinfri kaffe"],
  "common-bean": [
    "svarte bønner",
    "kidneybønner",
    "pintobønner",
    "brekkbønner",
    "aspargesbønner",
    "grønne bønner",
    "hvite bønner",
    "cannellinibønner",
    "brune bønner",
    "borlottibønner",
  ],
  coriander: ["korianderfrø"],
  corn: ["sukkermais", "popkorn", "polenta", "maismel", "maisstivelse"],
  cucumber: ["slangeagurk", "sylteagurk"],
  currant: ["solbær", "hvitrips"],
  "dragon-fruit": ["pitahaya"],
  elderberry: ["hylleblomst"],
  endive: ["julesalat"],
  fava: ["favabønne", "hestebønne"],
  fennel: ["fennikelfrø"],
  flax: ["linfrø"],
  garlic: ["hvitløkspulver"],
  ginger: ["ingefærpulver"],
  grape: ["rosiner", "sultanrosiner"],
  "hubbard-squash": ["hubbard"],
  kale: ["palmekål", "svartkål"],
  kiwi: ["kiwifrukt"],
  leek: ["purreløk"],
  lentil: ["røde linser", "grønne linser"],
  lettuce: ["issalat", "isbergsalat", "romansalat", "bindsalat"],
  lime: ["limefrukt"],
  lima: ["smørbønne"],
  lychee: ["lychee"],
  mandarin: ["klementin", "tangerin"],
  melon: ["honningmelon", "kantalupp"],
  mint: ["grønnmynte", "peppermynte"],
  mung: ["bønnespirer"],
  mustard: ["sennepsfrø"],
  nutmeg: ["muskatnøtt", "muskatblomme"],
  oat: ["havregryn", "havremelk", "havregrøt", "havremel"],
  olive: ["grønn oliven", "svart oliven", "kalamata"],
  onion: ["sjalottløk", "rødløk", "vårløk", "gul løk", "kepaløk"],
  orange: ["blodappelsin"],
  parsley: ["kruspersille", "bladpersille"],
  "passion-fruit": ["maracuja", "passionsfrukt"],
  "pattypan-squash": ["pattypan"],
  pea: ["erter", "sukkerert", "snøert", "hageert"],
  peach: ["nektarin"],
  peanut: ["peanøttsmør", "jordnøtt"],
  persimmon: ["persimon", "sharon"],
  "pine-nut": ["pinjenøtt"],
  plum: ["sviske"],
  potato: ["nypotet", "mandelpotet", "potetmel"],
  pumpkin: ["gresskarkjerner"],
  radish: ["daikon", "hvit reddik"],
  rice: ["hvit ris", "brun ris", "fullkornsris", "jasminris", "basmatiris", "risnudler", "rismel"],
  rye: ["rugmel"],
  seaweed: ["tare", "nori", "wakame", "kombu"],
  sesame: ["sesamfrø", "tahini"],
  shiitake: ["shiitakesopp"],
  sorghum: ["durra"],
  soy: ["soyabønne", "tofu", "tempeh", "edamame", "miso", "soyasaus"],
  spelt: ["speltmel", "farro"],
  "star-fruit": ["karambole"],
  "sweet-potato": ["batat"],
  tea: ["svart te", "grønn te", "matcha"],
  tomato: ["kirsebærtomat", "cherrytomat", "soltørket tomat", "tomatpuré", "passata"],
  truffle: ["svart trøffel", "hvit trøffel"],
  vanilla: ["vaniljestang"],
  watercress: ["vannkarse"],
  wheat: ["hvetemel", "pasta", "bulgur", "couscous", "semulegryn"],
  zucchini: ["zucchini"],
  cherry: ["morell", "surkirsebær"],
};
